### ISSUE TITLE
/bin/sh: nproc: command not found

### ISSUE THREAD

**Issue by int-index** [nh2/hackage-download#1]
When running the script, I get this output:

```
xargs -P 100 -n 50 wget --quiet < _urls.txt
xargs: wget: No such file or directory
find . -name '*.tar.gz' | xargs -P$(nproc) -I '{}' sh -c 'echo {}; tar -xf {}; rm -f {}'
/bin/sh: nproc: command not found
xargs: max. processes must be >0
```

**Comment by TravisCardwell** [comment]
The `nproc` command is part of the [GNU core utilities](https://www.gnu.org/software/coreutils/) and should be installed on any Linux system.  Perhaps you are using a different OS?  A simple workaround is to create an alias to a command that gets the number of cores on your platform.  For example, the following should work on MacOS:

    alias nproc='sysctl -n hw.logicalcpu'

@nh2 Since the script is in Python, you can use Python instead of `nproc` for better cross-platform support.  Use [`multiprocessing.cpu_count()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.cpu_count).

    >>> import multiprocessing
    >>> multiprocessing.cpu_count()
    4

**Comment by nh2** [comment]
@TravisCardwell Good suggestion, I've implemented that.

I've also added some extra logic to check for required programs and complain loudly.

@int-index if you rerun now, it should tell you what it needs.
